# Book settings
title: GIS and Spatial Methods in R
author: David Orme
page_authors: true

# Some cells take a while to run
execute:
  timeout: 10000

# Configure sphinx
sphinx:
  config:
    myst_heading_anchors: 3